### ISSUE TITLE
Speedhack mod gives inaccurate progress.

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [Dimava/dimava.github.io#4]
I've been working on the Gen3 Stone Hut problem. Which is helpful because it provides a quantifiable end state (seconds from completion).

When I run it without the mod, I end up 4s short of completion when I die.

When I ran the exact same run at 5x speed, I ended up gaining about another 10 seconds over the course of the generation. I can't say where the slippage is occuring, but it's there.

Running it at 2x speed had less of an overall effect, but still substantial, and I got the same effect using the timeskips as well.

---------------------------------

Wiping a save and then running the folloeing sequence is enough to see a difference:

berry, wood, berry, wood, berry, explore, explore.

5x speed did it 1 in-game-second faster.

**Comment by Dimava** [comment]
I'm now testing if the offline progress is faster then normal progress (by starting an all-auto online vs offline run)

If this is caused by incorrect *offline* progress calculations, it's not a bug, and can be used for speedruns
![image](https://user-images.githubusercontent.com/20068737/143888515-7cc4bf1c-8ab2-4c03-8a3c-6ae65abd23ab.png)

If this is caused by the incorrect *online* progress calculations, I'll have to fix this by forcing game ticks to run more often
